version: "3.8"
services:
 nginx:
  container_name: nginx
  image: nginx:latest
  ports:
   - target: 80
     published: 80
  volumes:
   - type: bind
     source: ./nginx.conf
     target: /etc/nginx/nginx.conf
  networks:
    - 'Petclinicnet'
  depends_on:
   - 'front-end'
 front-end:
  image: qaedd/spring-petclinic-angular:latest
  build: ./SPRING-PETCLINIC-ANGULAR
  ports:
  - published: 8080
    target: 8080
  networks:
    - 'Petclinicnet'
  depends_on:
    - 'back-end'
 back-end:
  image: springcommunity/spring-petclinic-rest
  ports:
  - published: 9966
    target: 9966
  networks:
    - 'Petclinicnet'
networks:
  Petclinicnet:


