apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1  
kind: Pod
metadata:
  name: frontend
  labels:  
    app: frontend
spec:
  containers:
  - name: frontend
    image: qaedd/spring-petclinic-angular:latest
    ports:
    - containerPort: 8080
